<style>
  p {
    color: #888;
/*    font-weight: normal;*/
    font-size: 13px;
    padding-left: 8px;
    padding-bottom: 5px;
  }
  div#demo-1 div {
    height: 380px;
  }
  div#demo-2 {
    float: left;
    height: 300px;
    margin-right: 10px;
    width: 398px;
  }
  div#demo-2 div {
    height: 300px;
  }
  div#demo-3 {
    float: left;
    width: 398px;
  }
  div#demo-3 div {
    height: 300px;
  }
</style>
<div id="global_notification">
  【系统通知】这个那个这个那个这个那个，这个那个这个那个，这个那个这个那个这个那个这个那个。
</div>
<div id="demo-1">
  <p>商品综合信息</p>
  <div class="block">
    
  </div>
</div>
<div id="demo-2">
  <p>最近7天访客来源</p>
  <div class="block">
    
  </div>
</div>
<div id="demo-3">
  <p>商品访问量排行</p>
  <div class="block">
    
  </div>
</div>