<div id="leftcol">
  <div class="info">
    <dl>
      <dt>橱窗总数</dt>
      <dd>40</dd>
    </dl>
    <dl>
      <dt>已推荐数量</dt>
      <dd>21</dd>
    </dl>
    <dl>
      <dt>架上商品数量</dt>
      <dd>21</dd>
    </dl>
    <dl>
      <dt>商品推荐率</dt>
      <dd>100<span class="percent">%</span></dd>
    </dl>
    <dl>
      <dt>橱窗利用率</dt>
      <dd>53<span class="percent">%</span></dd>
    </dl>
    <div class="cb"></div>
  </div>
  <div class="stats">
    过去24小时推荐次数
    过去7天推荐次数
  </div>
  <div class="settings">
    
  </div>
</div>
<div id="rightcol">
  <dl class="help">
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
    <dt>帮助条目</dt>
    <dd>
      如何如何如何如何，如何如何如何如何，如何如何如何如何，如何如何如何如何。
    </dd>
  </dl>
</div>